In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv('data/ch2_scores_em.csv',index_col='student number')

In [3]:
en_scores = np.array(df['english'])[:10]
ma_scores = np.array(df['mathematics'])[:10]
scores_df = pd.DataFrame({'english':en_scores,
                          'mathematics':ma_scores
                          },
                         index=pd.Index(['A','B','C','D','E','F','G','H','I','J'],name = 'student'))

scores_df

english  mathematics
student                      
A             42           65
B             69           80
C             56           63
D             41           63
E             57           76
F             48           60
G             65           81
H             49           66
I             65           78
J             58           82

In [5]:
summary_df = scores_df.copy()
summary_df['english_deviation'] = summary_df['english'] - summary_df['english'].mean()
summary_df['mathematics_deviation'] = summary_df['mathematics'] - summary_df['mathematics'].mean()
summary_df['product of deviations'] = summary_df['english_deviation'] * summary_df['mathematics_deviation']

In [6]:
summary_df

english  mathematics  english_deviation  mathematics_deviation   
student                                                                   
A             42           65              -13.0                   -6.4  \
B             69           80               14.0                    8.6   
C             56           63                1.0                   -8.4   
D             41           63              -14.0                   -8.4   
E             57           76                2.0                    4.6   
F             48           60               -7.0                  -11.4   
G             65           81               10.0                    9.6   
H             49           66               -6.0                   -5.4   
I             65           78               10.0                    6.6   
J             58           82                3.0                   10.6   

         product of deviations  
student                         
A                         83.2  
B                        120.4  
C                         -8.4  
D                        117.6  
E                          9.2  
F                         79.8  
G                         96.0  
H                         32.4  
I                         66.0  
J                         31.8

# 공분산

In [7]:

summary_df['product of deviations'].mean()

62.8

In [8]:
np.cov(en_scores,ma_scores, ddof=0)

array([[86.  , 62.8 ],
       [62.8 , 68.44]])

In [ ]:
# array([[86.(영어분산) , 62.8 ],
    #    [62.8 , 68.44]])

In [23]:
%precision 

'%r'

In [24]:
np.var(ma_scores,ddof=0)


68.44000000000001

# 상관계수


In [25]:
np.cov(en_scores,ma_scores, ddof=0)[0,1] / (np.std(en_scores) *np.std(ma_scores))

0.8185692341186713

In [26]:
# 넘파이로 구한것
np.corrcoef(en_scores,ma_scores)

array([[1.        , 0.81856923],
       [0.81856923, 1.        ]])

In [27]:
# 판다스로 구한것
scores_df.corr()

english  mathematics
english      1.000000     0.818569
mathematics  0.818569     1.000000